tap "aws/tap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "act"
brew "anyenv"
brew "argocd"
brew "awscli"
brew "bat"
brew "ffmpeg"
brew "gh"
brew "ghq"
brew "git"
brew "git-secrets"
brew "go"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "mosquitto"
brew "mysql"
brew "nginx"
brew "peco"
brew "podman"
brew "starship"
brew "tektoncd-cli"
brew "telnet"
brew "tree"
brew "watch"
brew "zsh-completions"
brew "aws/tap/aws-sam-cli"
cask "alfred"
cask "clipy"
cask "discord"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "visual-studio-code"
cask "zoom"
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "RunCat", id: 1429033973
mas "Slack", id: 803453959
