#!/usr/bin/env sh

# Layout config
yabai -m config window_gap                   4
yabai -m config window_placement             second_child
yabai -m config layout                       bsp
# yabai -m config bottom_padding               100

# set float layout for MBP display
space_indices_on_mbp_display="$(
    yabai -m query --displays | jq -e 'map(select(.uuid == "A31D52CE-BF35-E23C-8BF3-E76F72E4E69D")) | .[0].spaces[]'
)"

# shellcheck disable=SC2066
for index in "$space_indices_on_mbp_display"; do
    yabai -m config --space "$index" layout stack
done

# Mouse
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise

# Debug
yabai -m config debug_output on

# Rules
yabai -m rule --add app="^Calendar$"           manage=off
yabai -m rule --add app="^Dictionary$"         manage=off
yabai -m rule --add app="^Disk Utility$"       manage=off
yabai -m rule --add app="^Postlab$"            manage=off
yabai -m rule --add app="^Simulator$"          manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Electron$"           manage=off
yabai -m rule --add app="^iTerm2$" manage=off

echo "yabai configuration loaded..."

killall limelight &> /dev/null
limelight --config ~/.config/limelight/limelightrc &> /dev/null &
