name: 'build'

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: install from Brewfile
      run: brew bundle

    - name: Check result
      run: |
        mv Brewfile Brewfile.archive
        brew bundle dump
        diff Brewfile Brewfile.archive
