name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: macos-latest

    steps:
    - name: Execute install script
      shell: bash
      run: |
        export ENV
        export HOMEBREW_BUNDLE_BREW_SKIP
        export HOMEBREW_BUNDLE_MAS_SKIP
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ega4432/dotfiles/main/install.sh)"
      env:
        # Skip installing Mac App Store and software that already installed in virtual environment
        # ref. https://github.com/actions/virtual-environments/blob/macOS-11/20220530.2/images/macos/macos-11-Readme.md
        ENV: ci
        HOMEBREW_BUNDLE_BREW_SKIP: 'awscli git go helm'
        HOMEBREW_BUNDLE_MAS_SKIP: 'GarageBand iMovie Keynote Kindle LINE Numbers Pages RunCat Slack Xcode'
